console.log("1");
var pepe = [];
pepe.push("ubaldiniubaldini");
pepe.push("ffffffffffff");
pepe.push("averahora");
pepe.push("Allo ?");
pepe.push("Alioiooiii");
pepe.push("pepepepeep");
pepe.push("<strong>hacking</stong>");
pepe.push("<label style='color:red;'>Hola! :)</label>");
//pepe.push("si al navegar a tu ip publica ves el router, quiere decir que el ruteo no anda y que no blockeaste la administracion remota del router (bad idea)");
//pepe.push("si al navegar ves IIS, es que no pusiste el puerto de desarrollo ...");
//pepe.push("si al navegar ves IIS, es que no pusiste el puerto de desarrollo ...");
pepe.push("<br><br>Felicitaciones!<br><br>");
pepe.push("aca?");
pepe.push("aca?");
pepe.push("anda 15:07");
pepe.push("<textarea rows=\"4\" cols=\"50\"> Aca se puede escribir sin que Tyto se entere ... :) </textarea>");
pepe.push("ahora anda en el 80!!! 15:11");
pepe.push(":)");
pepe.push("test");
pepe.push(":)");
pepe.push("<br><a href='http://batateishon.hopto.org'>Link a esta pagina</a><br>");
pepe.push("https://www.youtube.com/watch?v=1q7U9C8Hq1g");
pepe.push("bajaonobaja");
pepe.push("&#22825;&#19979;&#30342;&#30693;&#32654;&#20043;&#29234;&#32654;&#65292; &#26031;&#24801;&#24050;&#65307;");
pepe.push("19:40");
pepe.push("si firma o'brian colapsa");
console.log("aca");
pepe.push("asdf");
pepe.push("esentoncescuandolashorasbajannnnn");
pepe.push("o no.....");
pepe.push("perepepepe");
pepe.push("migrado");
pepe.push("migrado");
pepe.push("async si?");
pepe.push("cabeceadagalacticajodemequefunciono");
pepe.push("jajajaasynclatenesadentro");
pepe.push("weeeeee are cabernassss may friendnddd");
pepe.push("css babbbbyyy");
pepe.push("yaura?");
pepe.push("entoncessi?");
pepe.push("faaaahhh, un mundo nuevo viehaaaa");
pepe.push("hola");
pepe.push("ahora si me deja");
pepe.push("como andas");
pepe.push("esta vivooooohhhh ESTA VIVOOOH");
pepe.push("test320498");
pepe.push("como andas");
pepe.push("como andas");
pepe.push("quehacescaradepantufloooooooo!!");
pepe.push("no se rompio");
pepe.push("asdasd");
pepe.push("afafafaf");
pepe.push("jhgjhg");
pepe.push("jhgjhg");
pepe.push("uhjh");
pepe.push("uhjh");
pepe.push("kjhkjhjhhh?");
pepe.push("kjhkjhjhhh?");
pepe.push("nani?");
pepe.push("?P");
pepe.push("jhgjhg   jhjh kh h");
pepe.push("el gato se fue a paris");
pepe.push("afafafaf");
pepe.push("porque no me deja poner signos");
pepe.push("a ver ahi?");
pepe.push("a ver ahi?");
pepe.push("ahi podes XD, signos de preguntas comas y puntos nomas");
pepe.push("y ahora de exclamacion tambien?!");
pepe.push("porque no me deja poner signos");
pepe.push("ggggg");
pepe.push("ggggg");
pepe.push("ggggg");
pepe.push("ahhhh, trataste de usar el de apertura de pregunta?");
pepe.push("tttttt");
pepe.push("ddddddd");
pepe.push("ddddddd");
pepe.push("ahhhh, trataste de usar el de apertura de pregunta?");
pepe.push("????�����");
pepe.push("fFfFfF");
pepe.push("987987987?");
pepe.push("que es esta mierda?");
pepe.push("agradece que la pagina no acepta asteriscos ni los simbolos pertinentes para el ascii art");
pepe.push("Hola tytitu");

pepe.push("afafafaf");
pepe.push("jhgjhg");
pepe.push("jhgjhgjhg");
pepe.push("kheonfsss");
pepe.push("jjjj");
pepe.push("jjjj");
pepe.push("jjjj");
pepe.push("jjjj");
pepe.push("noseolvidendevandor");
pepe.push("noseolvidendevandor");
pepe.push("noseolvidendevandor");
pepe.push("noseolvidendevandor");
pepe.push("mevareinciar cada vez que ponga algo?");
pepe.push("funcoelignore?");
pepe.push("mmmmmm");
pepe.push("vaaaamooo el ignoreeeeehhhh");
pepe.push("averlosurls");
pepe.push("Amiguitoooo!!");
pepe.push("kaceh cabezonnn?");
pepe.push("Amiguitoooo!!");
pepe.push("Amiguitoooo!!");
pepe.push("jaja, lo tengo que cambiar para que no vuelva a mandar el mensaje cuando actualizas la pagina XD");
pepe.push("ahhh, a verrrr, pera");
pepe.push("ahhh, a verrrr, pera");
pepe.push("aaaahora creo que si");
pepe.push("wiiiiiiii");
